name: Debug Tauri Keys

on:
  push

jobs:
  check-keys:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Compare Keys
        run: |
          # Extract config key
          $config = Get-Content -Path "src-tauri/tauri.conf.json" | ConvertFrom-Json
          $configKey = $config.plugins.updater.pubkey
          echo "Config public key from tauri.conf.json:"
          echo $configKey
          echo "-----"
          
          # Use expected public key from secrets
          $expectedPubKey = "${{ secrets.TAURI_SIGNING_PUBLIC_KEY }}"
          echo "Expected public key from secrets:"
          echo $expectedPubKey
          echo "-----"
          
          if ($configKey -eq $expectedPubKey) {
            echo "✅ SUCCESS: Public keys match!"
          } else {
            echo "❌ ERROR: Public keys do not match!"
            echo "Update your tauri.conf.json with the correct public key."
          }
        shell: pwsh