name: Debug Tauri Keys

on:
  push

jobs:
  check-keys:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup signing key file
        run: |
          $keyData = "${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}"
          $keyPath = "${{ github.workspace }}\signing-key.key"
          Set-Content -Path $keyPath -Value $keyData
        shell: pwsh
        
      - name: Compare Key Values
        run: |
          # Extract config key
          $config = Get-Content -Path "src-tauri/tauri.conf.json" | ConvertFrom-Json
          $configKey = $config.plugins.updater.pubkey
          echo "Config public key from tauri.conf.json:"
          echo $configKey
          echo "-----"
          
          # Display private key first few characters (safely)
          $keyData = Get-Content -Path "${{ github.workspace }}\signing-key.key" -Raw
          $keyPreview = $keyData.Substring(0, [Math]::Min(20, $keyData.Length)) + "..."
          echo "Private key preview (first few chars):"
          echo $keyPreview
          echo "-----"
          
          echo "To extract the public key from your private key locally, run:"
          echo "cargo tauri signer pubkey path/to/your/key.key"
          echo ""
          echo "Then compare it with the config key to ensure they match."
        shell: pwsh